{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "81a9181e-7ef3-469e-bc06-2338ca53b67a",
   "metadata": {},
   "outputs": [],
   "source": [
    "from ultralytics import YOLO\n",
    "import os\n",
    "import matplotlib.pyplot as plt\n",
    "from ray import tune"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3651a1ab-bb75-4786-b5ec-27e2e9ed7988",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div class=\"tuneStatus\">\n",
       "  <div style=\"display: flex;flex-direction: row\">\n",
       "    <div style=\"display: flex;flex-direction: column;\">\n",
       "      <h3>Tune Status</h3>\n",
       "      <table>\n",
       "<tbody>\n",
       "<tr><td>Current time:</td><td>2024-12-10 14:36:49</td></tr>\n",
       "<tr><td>Running for: </td><td>00:00:42.81        </td></tr>\n",
       "<tr><td>Memory:      </td><td>14.5/15.3 GiB      </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "    <div class=\"systemInfo\">\n",
       "      <h3>System Info</h3>\n",
       "      Using AsyncHyperBand: num_stopped=0<br>Bracket: Iter 30.000: None | Iter 10.000: None<br>Logical resource usage: 8.0/16 CPUs, 0/1 GPUs (0.0/1.0 accelerator_type:G)\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "<div class=\"messages\">\n",
       "  <h3>Messages</h3>\n",
       "  : ***LOW MEMORY*** less than 10% of the memory on this node is available for use. This can cause unexpected crashes. Consider reducing the memory used by your application or reducing the Ray object store size by setting `object_store_memory` when calling `ray.init`.\n",
       "  \n",
       "  Number of errored trials: 10<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name       </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                                                                            </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>_tune_6a15c_00000</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00000_0_lr0=0.0418_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00001</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00001_1_lr0=0.0674_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00002</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00002_2_lr0=0.0486_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00003</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00003_3_lr0=0.0130_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00004</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00004_4_lr0=0.0731_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00005</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00005_5_lr0=0.0041_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00006</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00006_6_lr0=0.0201_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00007</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00007_7_lr0=0.0908_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00008</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00008_8_lr0=0.0638_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "<tr><td>_tune_6a15c_00009</td><td style=\"text-align: right;\">           1</td><td>C:/Users/YASIRU~1/AppData/Local/Temp/ray/session_2024-12-10_14-35-59_053656_9284/artifacts/2024-12-10_14-36-05/_tune_2024-12-10_14-36-05/driver_artifacts/_tune_6a15c_00009_9_lr0=0.0794_2024-12-10_14-36-06/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".messages {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  padding-left: 1em;\n",
       "  overflow-y: auto;\n",
       "}\n",
       ".messages h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n",
       "\n",
       "  </div>\n",
       "  <div class=\"hDivider\"></div>\n",
       "  <div class=\"trialStatus\">\n",
       "    <h3>Trial Status</h3>\n",
       "    <table>\n",
       "<thead>\n",
       "<tr><th>Trial name       </th><th>status  </th><th>loc            </th><th style=\"text-align: right;\">       lr0</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>_tune_6a15c_00000</td><td>ERROR   </td><td>127.0.0.1:52284</td><td style=\"text-align: right;\">0.0418234 </td></tr>\n",
       "<tr><td>_tune_6a15c_00001</td><td>ERROR   </td><td>127.0.0.1:52336</td><td style=\"text-align: right;\">0.0674001 </td></tr>\n",
       "<tr><td>_tune_6a15c_00002</td><td>ERROR   </td><td>127.0.0.1:14212</td><td style=\"text-align: right;\">0.0486326 </td></tr>\n",
       "<tr><td>_tune_6a15c_00003</td><td>ERROR   </td><td>127.0.0.1:38828</td><td style=\"text-align: right;\">0.0129528 </td></tr>\n",
       "<tr><td>_tune_6a15c_00004</td><td>ERROR   </td><td>127.0.0.1:43052</td><td style=\"text-align: right;\">0.0730671 </td></tr>\n",
       "<tr><td>_tune_6a15c_00005</td><td>ERROR   </td><td>127.0.0.1:51740</td><td style=\"text-align: right;\">0.00413553</td></tr>\n",
       "<tr><td>_tune_6a15c_00006</td><td>ERROR   </td><td>127.0.0.1:52808</td><td style=\"text-align: right;\">0.0200844 </td></tr>\n",
       "<tr><td>_tune_6a15c_00007</td><td>ERROR   </td><td>127.0.0.1:51436</td><td style=\"text-align: right;\">0.0907948 </td></tr>\n",
       "<tr><td>_tune_6a15c_00008</td><td>ERROR   </td><td>127.0.0.1:51392</td><td style=\"text-align: right;\">0.0638052 </td></tr>\n",
       "<tr><td>_tune_6a15c_00009</td><td>ERROR   </td><td>127.0.0.1:46140</td><td style=\"text-align: right;\">0.0794123 </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "  </div>\n",
       "</div>\n",
       "<style>\n",
       ".tuneStatus {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".tuneStatus .systemInfo {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       ".tuneStatus .trialStatus {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".tuneStatus .hDivider {\n",
       "  border-bottom-width: var(--jp-border-width);\n",
       "  border-bottom-color: var(--jp-border-color0);\n",
       "  border-bottom-style: solid;\n",
       "}\n",
       ".tuneStatus .vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-10 14:36:14,475\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00000\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=52284, ip=127.0.0.1, actor_id=a93598582db7e22f856911dd01000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:14,482\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00001\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=52336, ip=127.0.0.1, actor_id=fadecde02380ce4cb11952f201000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:23,653\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00002\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=14212, ip=127.0.0.1, actor_id=38b3e53e8d08eb3281c2f07901000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:23,657\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00003\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=38828, ip=127.0.0.1, actor_id=53814205086bb571aa5bf8e201000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:32,888\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00005\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=51740, ip=127.0.0.1, actor_id=3c70b6ab655cb946f024998901000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:32,894\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00004\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=43052, ip=127.0.0.1, actor_id=0433fc5ae681a3f894867e0101000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:40,980\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00006\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=52808, ip=127.0.0.1, actor_id=c1d93f5951f0623f30d28f9e01000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:40,985\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00007\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=51436, ip=127.0.0.1, actor_id=302759fe0b7b60ae170ff20f01000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:49,267\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00008\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=51392, ip=127.0.0.1, actor_id=8e6917d340a67c618bd889e601000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:49,274\tERROR tune_controller.py:1331 -- Trial task failed for trial _tune_6a15c_00009\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2755, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\worker.py\", line 906, in get_objects\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AssertionError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=46140, ip=127.0.0.1, actor_id=b976492fb77f30291b72277b01000000, repr=_tune)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1879, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1820, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 331, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\air\\_internal\\util.py\", line 107, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 45, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 250, in _trainable_func\n",
      "    output = fn()\n",
      "             ^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\tuner.py\", line 106, in _tune\n",
      "    results = model_to_train.train(**config)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\model.py\", line 800, in train\n",
      "    self.trainer = (trainer or self._smart_load(\"trainer\"))(overrides=args, _callbacks=self.callbacks)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\engine\\trainer.py\", line 103, in __init__\n",
      "    self.device = select_device(self.args.device, self.args.batch)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 218, in select_device\n",
      "    s += f\"{'' if i == 0 else space}CUDA:{d} ({get_gpu_info(i)})\\n\"  # bytes to MB\n",
      "                                               ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\ultralytics\\utils\\torch_utils.py\", line 129, in get_gpu_info\n",
      "    properties = torch.cuda.get_device_properties(index)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Yasiru Fernando\\.conda\\envs\\torch-env\\Lib\\site-packages\\torch\\cuda\\__init__.py\", line 526, in get_device_properties\n",
      "    raise AssertionError(\"Invalid device id\")\n",
      "AssertionError: Invalid device id\n",
      "2024-12-10 14:36:49,290\tINFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to 'E:/AIT/Semester 1 - AUG24/Deep Learning for Computer Vision/Project/DLCV Project/runs/detect/tune/_tune_2024-12-10_14-36-05' in 0.0105s.\n",
      "2024-12-10 14:36:49,327\tERROR tune.py:1037 -- Trials did not complete: [_tune_6a15c_00000, _tune_6a15c_00001, _tune_6a15c_00002, _tune_6a15c_00003, _tune_6a15c_00004, _tune_6a15c_00005, _tune_6a15c_00006, _tune_6a15c_00007, _tune_6a15c_00008, _tune_6a15c_00009]\n",
      "2024-12-10 14:36:49,328\tINFO tune.py:1041 -- Total run time: 43.71 seconds (42.80 seconds for the tuning loop).\n"
     ]
    }
   ],
   "source": [
    "# Load the YOLO model\n",
    "model = YOLO('yolo11n.pt')  \n",
    "\n",
    "result_grid = model.tune(data=\"instruments.yaml\", use_ray=True)\n",
    "\n",
    "# # Run Ray Tune on the model\n",
    "# result_grid = model.tune(\n",
    "#     data=\"./instruments.yaml\",\n",
    "#     space={\"lr0\": tune.uniform(1e-5, 1e-1)},\n",
    "#     epochs=50,\n",
    "#     use_ray=True,\n",
    "# )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99a13c50-9ebe-4e4c-a533-766985aaae6f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "torch-env",
   "language": "python",
   "name": "torch-env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
